services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: convoca
      POSTGRES_PASSWORD: convoca
      POSTGRES_DB: convocafinder
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "convoca"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # ¡Ojo! SQLAlchemy URL con psycopg2
      DATABASE_URL: postgresql+psycopg2://convoca:convoca@db:5432/convocafinder
      REDIS_URL: redis://redis:6379/0
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      # Pydantic Settings espera lista JSON para arrays
      CORS_ORIGINS: '["http://localhost:3000"]'
    depends_on:
      - db
      - redis
      - mailhog

  worker:
    build: ./backend
    command: python -m app.worker
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://convoca:convoca@db:5432/convocafinder
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    command: npm run dev -- -H 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      # El navegador (en tu host) debe hablar a localhost
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend

volumes:
  db_data:
  redis_data:
  frontend_node_modules:
